#pragma once

#include "sdkconfig.h"

#define CATDEX_SCHEMA_VERSION 1U

#define CATDEX_MAX_SPECIES 12
#define CATDEX_MAX_CAPTURED 64
#define CATDEX_MAX_SKILLS 4

#define CATDEX_NAME_LEN 24
#define CATDEX_LORE_LEN 96

#define CATDEX_UI_LINE_COUNT 8
#define CATDEX_UI_LINE_LEN 64

#define CATDEX_THUMB_WIDTH 80
#define CATDEX_THUMB_HEIGHT 80

#define CATDEX_APP_TICK_MS 250

#ifdef CONFIG_CATDEX_ENABLE_INPUT_DEMO
#define CATDEX_ENABLE_INPUT_DEMO 1
#else
#define CATDEX_ENABLE_INPUT_DEMO 0
#endif

#ifdef CONFIG_CATDEX_INPUT_ADC_LOG_RAW
#define CATDEX_INPUT_ADC_LOG_RAW 1
#else
#define CATDEX_INPUT_ADC_LOG_RAW 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_TEXT_LOG_ONLY
#define CATDEX_DISPLAY_TEXT_LOG_ONLY 1
#else
#define CATDEX_DISPLAY_TEXT_LOG_ONLY 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_LOG_MIRROR
#define CATDEX_DISPLAY_LOG_MIRROR 1
#else
#define CATDEX_DISPLAY_LOG_MIRROR 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_BOOT_TEST
#define CATDEX_DISPLAY_BOOT_TEST 1
#else
#define CATDEX_DISPLAY_BOOT_TEST 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_BACKLIGHT_ACTIVE_HIGH
#define CATDEX_DISPLAY_BACKLIGHT_ACTIVE_HIGH 1
#else
#define CATDEX_DISPLAY_BACKLIGHT_ACTIVE_HIGH 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_BACKLIGHT_SWEEP
#define CATDEX_DISPLAY_BACKLIGHT_SWEEP 1
#else
#define CATDEX_DISPLAY_BACKLIGHT_SWEEP 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_SWAP_XY
#define CATDEX_DISPLAY_SWAP_XY 1
#else
#define CATDEX_DISPLAY_SWAP_XY 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_MIRROR_X
#define CATDEX_DISPLAY_MIRROR_X 1
#else
#define CATDEX_DISPLAY_MIRROR_X 0
#endif

#ifdef CONFIG_CATDEX_DISPLAY_MIRROR_Y
#define CATDEX_DISPLAY_MIRROR_Y 1
#else
#define CATDEX_DISPLAY_MIRROR_Y 0
#endif

#define CATDEX_DEMO_SEED_ON_EMPTY 1

#define CATDEX_MIN_CONFIDENCE_TO_CAPTURE 35

#ifndef CONFIG_CATDEX_INPUT_ADC_TOLERANCE_MV
#define CONFIG_CATDEX_INPUT_ADC_TOLERANCE_MV 220
#endif

#ifndef CONFIG_CATDEX_CAMERA_RESET_GPIO
#define CONFIG_CATDEX_CAMERA_RESET_GPIO -1
#endif

#ifndef CONFIG_CATDEX_CAMERA_PWDN_GPIO
#define CONFIG_CATDEX_CAMERA_PWDN_GPIO -1
#endif

#ifndef CONFIG_CATDEX_DISPLAY_BOOT_TEST_MS
#define CONFIG_CATDEX_DISPLAY_BOOT_TEST_MS 240
#endif

#ifndef CONFIG_CATDEX_DISPLAY_X_GAP
#define CONFIG_CATDEX_DISPLAY_X_GAP 0
#endif

#ifndef CONFIG_CATDEX_DISPLAY_Y_GAP
#define CONFIG_CATDEX_DISPLAY_Y_GAP 0
#endif

#define CATDEX_CAMERA_RESET_GPIO CONFIG_CATDEX_CAMERA_RESET_GPIO
#define CATDEX_CAMERA_PWDN_GPIO CONFIG_CATDEX_CAMERA_PWDN_GPIO
#define CATDEX_DISPLAY_BOOT_TEST_MS CONFIG_CATDEX_DISPLAY_BOOT_TEST_MS
#define CATDEX_DISPLAY_X_GAP CONFIG_CATDEX_DISPLAY_X_GAP
#define CATDEX_DISPLAY_Y_GAP CONFIG_CATDEX_DISPLAY_Y_GAP
